### ISSUE TITLE
Health check URI

### ISSUE THREAD

**Issue by ihard** [lomik/graphite-clickhouse#118]
Is there any URI for determining the liveliness of the application?
Prometheus support https://prometheus.io/docs/prometheus/latest/management_api/
Health check
GET /-/healthy
This endpoint always returns 200 and should be used to check Prometheus health.

Readiness check
GET /-/ready
This endpoint returns 200 when Prometheus is ready to serve traffic (i.e. respond to queries).

But none of them are available in graphite-clickhouse.

**Comment by Felixoid** [comment]
Hey.

tl;dr: I think, GCH already has an API to check availability.

I guess you could use any of the handlers:

- `/metrics/find/?query=*`
- `/render/?target=some.metric&from=0&until=0`

I don't check the GCH, since it's installed on the same host as carbonapi, but for carbonapi checking, I have the following nginx snippet in the config

```
location =/monitor {
    rewrite              ^/monitor$ /render?format=json&target=definitely.non.existent.metric break;
    access_log           /var/log/nginx/graphite-lb-access.log;
    proxy_pass           http://localhost:8080;
    proxy_read_timeout   3600s;
    include              proxy_params;
}
```

**Comment by ihard** [comment]
The URI
`/metrics/find/?query=*`
 looks like an easy enough option to check, thanks. 
Сarbonapi has a uri /lb_check to check from the load balancer.

**Comment by Felixoid** [comment]
well... It doesn't really check, if something behind it is alive, unfortunately

https://github.com/go-graphite/carbonapi/blob/main/cmd/carbonapi/http/lbcheck_handler.go#L16

So, if GCH/CH behind is dead, the LB still will treat it as alive :-j
