### ISSUE TITLE
clickhouse doesn't honour rollup.xml file  

### ISSUE THREAD

**Issue by ervikrant06** [lomik/graphite-clickhouse#132]
I guess it's worth to mention in this repo about the issues

https://github.com/ClickHouse/ClickHouse/issues/21106
https://github.com/ClickHouse/ClickHouse/issues/20087

I am surprised to know that thr is no guarantee of reducing the retentions of metrics in clickhouse DB based on rollup.xml? I understand delete of metrics is difficult, we have to apply custom solution for it but it should have take care of reducing the retention of metrics. 

btw graphite-ch-optimizer is running from past 7 days and it hasn't done any merges yet

~~~
$ kubectl logs graphite-ch-optimizer-7986db667b-ztj7v | grep 'Merges will be applied:' | awk -F'=' '{print $NF}'  | sort | uniq -c
    285 "Merges will be applied: 0"
~~~

cc: @Felixoid

**Comment by ervikrant06** [comment]
Also in second link it's mentioned that for rollup.xml avg may not give accurate results. I switched to any instead of avg.

**Comment by Felixoid** [comment]
> I guess it's worth to mention in this repo about the issues

No, I don't think spamming random repositories with tickets is proper behavior. Your issue is a misunderstanding of the GraphiteMergeTree behavior and infrastructure around the engine.

Denis described the basics [here](https://github.com/ClickHouse/ClickHouse/issues/21106#issuecomment-784511428), and what should be done is tuning graphite-ch-optimizer, since it's the only way currently to get retention applied reliably.

So, first, please run `graphite-ch-optimizer --help` and read the description, `--optimize-interval` particularly. When you run the service in debug mode [here](https://github.com/innogames/graphite-ch-optimizer/issues/17#issuecomment-778115809), you see it in the query at `[clickhouse][connect=1][send query]`. It returns nothing, that's why you don't have the optimizations applied. But if `OPTIMIZE shard_01.graphite FINAL` works (it's not clear BTW from the [comment](https://github.com/ClickHouse/ClickHouse/issues/20087#issuecomment-783421548)), then the state `clickhouse doesn't honour rollup.xml file` is completely untrue. So stop claiming it, please.

> Also in second link it's mentioned that for rollup.xml avg may not give accurate results. I switched to any instead of avg.

It's true, Denis [mentioned](https://github.com/ClickHouse/ClickHouse/issues/20087#issuecomment-773602914) it in the context that `avg` _may be less accurate than in whisper_, because of lack of the number of points after . But it is not related anyhow to your problem, and still would be much more precise, than `any`. You are completely free to use any function from [the list](https://clickhouse.tech/docs/en/sql-reference/aggregate-functions/reference/). They will do the job with the best effort but may be inaccurate in the math meaning because of internal implementation.

You are very welcome to ask questions regarding graphite-ch-optimizer in the ticket you've opened.

**Comment by ervikrant06** [comment]
My apologies no intentions of spreading false information. Will continute working in issue mentioned in your comment. Because of my wrong interpretation I opened this issue in hope to help others. Again sorry for any confusion.

**Comment by Felixoid** [comment]
No problem. The `ClickHouse+Graphite` stack is very stable and tested in many companies. I think there still some edge-cases like https://github.com/ClickHouse/ClickHouse/issues/5582, but it's **a rare situation** for frequent inserts of the same metric name in one data point.

The main point about \*MergeTree engines family, it's merged **eventually**. You shouldn't even care about the fact if it's not optimized _now_. If you do, tuning graphite-ch-optimizer to be more aggressive is the solution.
