### ISSUE TITLE
Tags performance

### ISSUE THREAD

**Issue by maxpolezhaev** [lomik/graphite-clickhouse#22]
Requests for tagged metrics are slow when there are many tags in ClickHouse. In our test case we had 3 tags and 10K values for each, metrics were generated for period of one year. So a `seriesByTag` request took about 1 second.

I found that graphite-clickhouse makes 2 queries to ClickHouse when processing seriesByTag requests:

1. Query to get Paths by tags (from graphite_tagged table).
  
2. Query to get metrics by these Paths.

The first query is pretty slow (0.6 s in our test). Can we make the second query without it, just doing
`WHERE Path LIKE '%tag1_name=tag2_value%' AND Path LIKE '%tag2_name=tag2_value'...` 
instead of 
`WHERE Path IN (<results of the first query>)`?
It is much faster, takes just 0.04 s on the same test data.

Maybe there are some cases when original queries are faster and it would be better to have a config option to enable the proposed changes.

Are there any issues with this? If no, then I can implement it and make a PR.

**Comment by Hipska** [comment]
Also came to this issue when doing a `seriesByTag` that results in a lot of paths. This time the ClickHouse server throws errors because the resulting query (`Path IN ( ..`) is too big.

**Comment by Felixoid** [comment]
Hello, colleagues.

Since the logic of a data fetching is slightly changed after ClickHouse internal aggregation was implemented, now it's necessary to first get the data locally, group metrics by the retention scheme, and only then send specific queries with proper step and aggregate function to the DB.

Although, #101 may address the issue mentioned here since benchmarks look promissing. It would be nice if you could test it and bring your feedback.

**Comment by Felixoid** [comment]
I assume this should be solved with #100, but feel free to open it in case of another opinion!
