### ISSUE TITLE
Debugging/improving poor performance?

### ISSUE THREAD

**Issue by mzealey** [lomik/graphite-clickhouse#81]
I'm currently using carbonapi & go-carbon but would like to switch to clickhouse for ingest performance. The following query takes <1s to run over the past 3h of data (each * expands to roughly 500 metrics):

```
aliasByNode(highestAverage(group( 
scale(divideSeriesLists($prefix.$group.$server.cloudlinux.*.counter.CPU,$prefix.$group.$server.cloudlinux.*.gauge.lCPU), 0.00001),         
divideSeriesLists($prefix.$group.$server.cloudlinux.*.counter.IOPS,$prefix.$group.$server.cloudlinux.*.gauge.lIOPS),         
divideSeriesLists($prefix.$group.$server.cloudlinux.*.counter.IO,$prefix.$group.$server.cloudlinux.*.gauge.lIO),         
divideSeriesLists($prefix.$group.$server.cloudlinux.*.gauge.NPROC,$prefix.$group.$server.cloudlinux.*.gauge.lNPROC),         
divideSeriesLists($prefix.$group.$server.cloudlinux.*.gauge.EP,$prefix.$group.$server.cloudlinux.*.gauge.lEP),         
divideSeriesLists($prefix.$group.$server.cloudlinux.*.gauge.MEMPHY,$prefix.$group.$server.cloudlinux.*.gauge.lMEMPHY)
)  , 10),4,6)
```

When I switch carbonapi to point at graphite-clickhouse it now takes ~27sec for the same query ie ~30-60* slower. How can I debug this and improve the performance?

**Comment by mzealey** [comment]
using the undocumented feature `sendGlobsAsIs` in carbonapi seems to fix this issue

**Comment by Civil** [comment]
If carbonapi you are talking about is go-graphite/carbonapi:

`sendGlobsAsIs` and `alwaysSendGlobsAsIs` are not documented, because it is present for compatibility reasons with carbonapi 0.10.0 and 0.11.0 where it was introduced and it will be removed in future versions.

The same effect you can achieve by setting `maxBatchSize` to 0, which is described here: https://github.com/go-graphite/carbonapi/blob/main/doc/configuration.md#upstreams (0 means unlimited).

Which is also present in example config for graphite-clickhouse: https://github.com/go-graphite/carbonapi/blob/main/doc/configuration.md#for-graphite-clickhouse

If that doesn't work like I've explained, please open a bug in go-graphite/carbonapi with your config example. I'm also open to any suggestions how to improve documentation to make it more clear that some settings are strongly preferred for some types of backends or requests.

**Comment by mzealey** [comment]
I had got `maxBatchSize` set to 0 but it was still passing all the metric expansions through. `sendGlobAsIs` fixed it to query clickhouse as regexp.
